# statistics_curriculum_notes
<b>Descriptive Statistics</b> lets us <i>describe</i> a set of data.<br>
The measures discussed focus on a single variable only and do not measure multiple variables at the same time or the interaction/relationship between variables.
### Measures of Central Tendency
Allow us to describe where the middle, or most mass, of a data set is. 
- <b>Mean</b> the average of all values (sum of values) / (number of values)
    - Can be influenced by outliers
        - <b>Trimmed Mean</b> the average after removing a certain percentage of outliers; less sensitive to outliers than the mean
- <b>Expected value</b> similar to average, but each value weighted by its probability sum of values X their probability)
- <b>Median</b> the center, or middle value
- <b>Mode</b> most frequently occuring value
    - <b>Bi-modal</b> when two values tie for mode

### Measures of Spread
Allow us to describe how spread out the data set it; gives us an idea of the shape of the data by describing how far apart points tend to be from the middle 
- <b>Min</b>
- <b>Max</b>
- <b>Range</b> [max] - [min]
- <b>Mean Absolute Deviation</b> average of deviations from a central point (usually the mean)
    - <i>we use 100 widgets a day +/- 10%</i>
- <b>Quantile</b> The <b>cut point(s)</b> that divide a  probability distribution into equally sized intervals
    - To divide our distribution into <b>n</b> equally sized intervals with <b>n - 1</b> cut point(s) or quantiles
    - To divide a distribution into two equally sized intervals (with one cut point/quantile), the median is the quantile/cut point
    - <b>Quartile</b> 4 intervals with 3 cut points/quartiles:
        - Q1: 25% of values are between min and Q1
        - Q2: 50% of values are between min and Q2
        - Q3: 75% of values are between min and Q3
            - <b>Interquartile Range</b> IQR, [Q3] - [Q1] or [75th percentile - 25th percentile] 
    - <b>Percentile</b> a quantile/cut point, split into 100 intervals
- <b>Variance</b> Average squared distance between each value and the mean; (sum(x[i] - mean)^2)/n
    - <b>Standard Deviation</b> Square root of the variance; measures absolute variability and can be compared with original values
- <b>Skew</b> measure of the asymmetry of the probability distribution of values
    - Left / Negative Skewed (mean < median)
    - Right Positive Skewed (median > mean)
    

# Simulation
np.random Functions
- <b>np.random.random</b> generates random number between 0 and 1
    - when integer, x is added as a parameter, it generates and array with a length of x
- <b>np.random.randint(n)</b> generates random number between 0 and n
    - using the <b>size=(x)</b> parameter, you can generate an array with a length of x
- <b>np.random.uniform(a, b)</b> generates a random float between a and b
- <b>np.random.choice([array])</b> generates random number from list parameter
    - using parameter---> size=(a,b) will generate a 2-d array with a rows and b columns
- <b>np.random.randn</b> generates numbers from standard normal distribution
- <b>np.random.normal</b> generates numbers from normal distribution with a specified mean and std dev


In [3]:
%matplotlib inline
import numpy as np
import pandas as pd

import viz

np.random.seed(29)

In [11]:
np.random.random()

0.7266357828275073

In [21]:
np.random.random(5)

array([0.3298106 , 0.47770002, 0.91953687, 0.30753744, 0.9849193 ])

In [14]:
np.random.rand(5, 2)

array([[5.83773058e-02, 4.09668926e-01],
       [6.10672274e-01, 2.55914875e-01],
       [2.85671928e-01, 6.84463747e-01],
       [8.40919735e-01, 8.09153420e-01],
       [6.34957546e-05, 9.23610095e-01]])

In [8]:
np.random.randint(100)

40

In [10]:
np.random.randint(100, size=(4))

array([96, 24, 85, 83])

In [31]:
np.random.uniform(2, 20)

7.32846918372726

In [16]:
np.random.choice([5, 8, 12, 4, 6, 1])

6

In [20]:
np.random.choice([3, 5, 7, 9], size=(3, 5))

array([[9, 3, 7, 3, 9],
       [3, 5, 9, 5, 3],
       [7, 9, 3, 7, 9]])